# Sofle v2.0w - nice!nano v2 + nice!view config

# Power
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# nice!view requires more LVGL memory
CONFIG_LV_Z_MEM_POOL_SIZE=4608

# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
